### ISSUE TITLE
Designer & linguist features off

### ISSUE THREAD

**Issue by awacha** [conda-forge/qt-main-feedstock#107]
Dear Feedstock developers,

I've noticed the "-DFEATURE_designer=OFF" and "-DFEATURE_linguist=OFF" CMake switches in the build.sh and bld.bat build scripts in the qt6 branch. Would it be possible to ship these two tools too? It turns out that the uic tool if PySide6 cannot be compiled without these, and therefore developing a Python program with PySide6 in a conda environment is a major pain. Or is there some reason, e.g. filename clashes between packages?

Thank you for your considerations.

Regards,

Andras

**Comment by jschueller** [comment]
it cannot be split easily because qttools is needed for cross-builds
it will be easier to wait for 6.5 and count on the new UNITY_BUILD support to speedup builds and enable it

**Comment by jschueller** [comment]
https://github.com/conda-forge/qt-main-feedstock/pull/142
