### ISSUE TITLE
Migration guide?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#12]
Can this be co-installed with the standard `qt` package?

If so, do we have any wisdom on how to migrate? I would like to start shedding the package size.

**Comment by andfoy** [comment]
We need to make `qt` a metapackage that pulls `qt-main` and `qt-webengine`. However, packages for webengine haven't been upload yet: https://github.com/conda-forge/qt-webengine-feedstock/issues/2

**Comment by ccordoba12** [comment]
But you can start using this package right now as a dependency of C++ only projects that don't require Webengine to work. The idea behind the split of `qt-main`/`qt-webengine` was precisely to reduce the installation size of those projects.

When @andfoy creates new packages for PyQt based on this one, the same could be done for Matplotlib, Qtconsole, etc.

**Comment by isuruf** [comment]
> But you can start using this package right now as a dependency of C++ only projects that don't require Webengine to work. 

No, we should do this globally as a migrator. Doing it ad hoc is only going to introduce incompatibilities between packages.

**Comment by ccordoba12** [comment]
> No, we should do this globally as a migrator. Doing it ad hoc is only going to introduce incompatibilities between packages.

Ok, I was not aware of that.

> Will there be a mechanism to allow parallel installation of Qt 5 and Qt 6?

That's not for this issue but I'm slightly -1 on it because it could be confusing for most users.

**Comment by hoechenberger** [comment]
> That's not for this issue but I'm slightly -1 on it because it could be confusing for most users.

Sorry, I didn't mean to hijack this – just thought it might fall under the label of "migration" too. Thank you for sharing your thoughts anyway! 👍

**Comment by Tobias-Fischer** [comment]
Now that https://github.com/conda-forge/qt-webengine-feedstock/issues/2 has been merged (hooray!), is the plan still to modify the qt feedstock to become a metapackage that lists both qt-main and qt-webengine listed, and then trigger a version migration in the pinnings feedstock?

**Comment by isuruf** [comment]
>  is the plan still to modify the qt feedstock to become a metapackage that lists both qt-main and qt-webengine listed

Yes

>  then trigger a version migration in the pinnings feedstock?

Yes, but the bot needs a mini-migrator to change `qt` dependency to `qt-main` in the feedstocks in the version migration.

**Comment by hmaarrfk** [comment]
I tried to build the qt metapackage, but unfortunately, qt-webengine is at 5.15.4 and qt-main will be at 5.15.3 soon.

Can we loosen the pin for 5.15.4 to constrain it to `qt 5.15.3|5.15.4`?

If so, I can make the repodata patch.
Once the patch is in, we can merge this: https://github.com/conda-forge/qt-webengine-feedstock/pull/5

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/254

**Comment by Tobias-Fischer** [comment]
I guess this issue can be closed @hmaarrfk?
