### ISSUE TITLE
Maintainability of aarch and ppc64le builds for qt5

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#188]
### Comment:

I've been building the qt5 builds for aarch and ppc64le.

Part of including those builds in conda-forge hinged on the fact that we would have a little more help in building them.

While I understand that people get busy, it has been delaying getting updates out for those on x86-64bit.

I would like to ping those interested:

- ppc64le @matthiasdiener
- aarch64 @Tobias-Fischer 

It may be that we can "trim" some of those builds to make migrations less "required" for aarch64 and ppc64le

For example, maybe we can remove `alsa`  or other dependencies making it less critical to hit every migration?

**Comment by Tobias-Fischer** [comment]
Hi @hmaarrfk - apologies for this! I'd be happy to build aarch64 when needed; please just ping me in the migration PRs that require aarch64 rebuilds.

**Comment by hmaarrfk** [comment]
ok, i've got the ones this time but thank you for acknowledging.

**Comment by matthiasdiener** [comment]
Same for me @hmaarrfk - I'm happy to run the ppc64le builds, but it's difficult to track when to build them. Please ping me when a ppc64le build is required.
