### ISSUE TITLE
Qt6 maybe should not depend on OpenGL

### ISSUE THREAD

**Issue by pgunn** [conda-forge/qt-main-feedstock#251]
### Comment:

OpenGL is a pretty troublesome dependency for software packaging; I realise that there may be performance (or feature) reasons for Qt6 to have an OpenGL dependency, but if it's not hard it'd be nice to either have alternate builds available without that dependency.

See also:
https://github.com/conda-forge/opencv-feedstock/issues/401#issuecomment-2027458207
https://github.com/flatironinstitute/CaImAn/issues/1312

**Comment by hmaarrfk** [comment]
FWIW, the effort in https://github.com/conda-forge/staged-recipes/pull/25919 might help things

**Comment by traversaro** [comment]
xref: https://github.com/conda-forge/qt-main-feedstock/pull/284

**Comment by hmaarrfk** [comment]
A pr to the qt6 branch is welcome so we can help get the process moving

**Comment by traversaro** [comment]
I guess this was fixed by https://github.com/conda-forge/qt-main-feedstock/pull/287 ?

**Comment by hmaarrfk** [comment]
Yes
