### ISSUE TITLE
 qtmutimedia and qtquick3d missing from windows 64 build  1 -- qt6

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#265]
### Comment:

- [ ] Merge recipe fix: https://github.com/conda-forge/qt-main-feedstock/pull/264
- [ ] Mark qt6-main 6.7.1 build 1 on windows broken -- https://github.com/conda-forge/admin-requests/pull/1006
- [ ] Mark qt6-multimedia 6.7.1 builds 0 and 1 on windows broken ????

cc: @mmcauliffe

**Comment by mmcauliffe** [comment]
It looks like https://github.com/conda-forge/qt-main-feedstock/pull/264 is passing and can be merged in, for longer term, should I create a staged recipe for qtquick3d?  For qt-charts, it's relying on that and if we remove qtmultimedia from 6.7.2, qt-charts will no longer be buildable.  Alternatively, could it be bundled into another related feedstock like https://github.com/conda-forge/qt-datavis3d-feedstock and have qt-charts dependent on that?  Is the eventual vision/vision for 6.7.2 to split off all extra modules to separate recipes, or bundled a bit more for specific areas (i.e., qt-multimedia has QtMultimedia and QtSpatialAudio right now, qt-datavis3d has QtDataVisualization and QtDataVisualizationQml)?

**Comment by hmaarrfk** [comment]
I think it makes sense to have a new recipe `qt6-qtquick3d` and have the other submodules depend on that.

We can add back if statements in this recipe to disable `quick3d`  from being built.
