### ISSUE TITLE
Break out qtquick3d from qt-main package

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#266]
### Comment:

It seems that it is GPL, which I think imposes more restrictions than we may want on this package.

https://doc.qt.io/qt-6/qtquick3d-index.html

Lets break it out and ensure that the following downstream packages depend on it correctly:

1. qt-multimedia
2. qt-charts

qt-multimedia should not hard depend on qt-quick3d for the same licensing reasons.

**Comment by jschueller** [comment]
good catch, I did not notice this one
