### ISSUE TITLE
Updated aarch64 packages

### ISSUE THREAD

**Issue by andfoy** [conda-forge/qt-main-feedstock#28]
### Comment:

Hi, per the last PR #26, the current aarch64 packages are now unsync'd. I've built the latest package, which is now available on my channel with the label `cf-copy`: https://anaconda.org/andfoy/qt-main/files. The logs, as usual, can be found here: https://drive.google.com/file/d/1bm9l7IM6G8FL32trk-d_iufYpUGDdluP/view?usp=sharing

I would appreciate the help of @conda-forge/core to upload this package. 

cc @hmaarrfk

**Comment by hmaarrfk** [comment]
[linux-aarch64-build.zip](https://github.com/conda-forge/qt-main-feedstock/files/8791863/linux-aarch64-build.zip)


Is there a flag we can provide to make the logs quieter?
