### ISSUE TITLE
Remove clang constraint on arm64

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/qt-main-feedstock#285]
Now that the upstream fix for https://bugreports.qt.io/browse/PYSIDE-2288 has landed in 6.5.1 (and apparently some 5.15.x), we should revert https://github.com/conda-forge/qt-main-feedstock/commit/2a5af89addb7d89cb6d8087034349d10146d87ea. There's some related commits mentioned in the issue, and some can be [found](https://github.com/search?q=repo%3Apyside%2Fpyside-setup+PYSIDE-2288&type=commits) on the repo

**Comment by hmaarrfk** [comment]
Done in https://github.com/conda-forge/qt-main-feedstock/pull/236
