### ISSUE TITLE
Builds are failing on aarch64 native

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#34]
### Comment:

I'm trying to compile thins on aarch64 since approxi June 1st, 2022, and it seems that the builds are failing:
[build.zip](https://github.com/conda-forge/qt-main-feedstock/files/8811030/build.zip)

Log attached if anybody wants to help sift.

@andfoy @ccordoba12

**Comment by andfoy** [comment]
I'll give it a run on my local machine

**Comment by hmaarrfk** [comment]
any results?

**Comment by hmaarrfk** [comment]
This is happening even with emulation:

```
g++ -o "../bin/qmake" main.o meta.o option.o project.o property.o ioutils.o proitems.o qmakebuiltins.o qmakeevaluator.o qmakeglobals.o qmakeparser.o qmakevfs.o pbuilder_pbx.o makefile.o makefiledeps.o metamakefile.o projectgenerator.o unixmake2.o unixmake.o mingw_make.o msbuild_objectmodel.o msvc_nmake.o msvc_objectmodel.o msvc_vcproj.o msvc_vcxproj.o winmakefile.o xmloutput.o qutfcodec.o qendian.o qglobal.o qlogging.o qmalloc.o qnumeric.o qoperatingsystemversion.o qrandom.o qabstractfileengine.o qbuffer.o qdatastream.o qdebug.o qdir.o qdiriterator.o qfile.o qfiledevice.o qfileinfo.o qfilesystemengine.o qfilesystementry.o qfsfileengine.o qfsfileengine_iterator.o qiodevice.o qsettings.o qtemporaryfile.o qtextstream.o qcborstreamwriter.o qcborvalue.o qjsoncbor.o qjsonarray.o qjsondocument.o qjsonobject.o qjsonparser.o qjsonvalue.o qmetatype.o qsystemerror.o qvariant.o quuid.o qarraydata.o qbitarray.o qbytearray.o qbytearraylist.o qbytearraymatcher.o qcalendar.o qgregoriancalendar.o qromancalendar.o qcryptographichash.o qdatetime.o qhash.o qlist.o qlocale.o qlocale_tools.o qmap.o qregexp.o qringbuffer.o qstringbuilder.o qstring.o qstringlist.o qversionnumber.o qvsnprintf.o qxmlstream.o qxmlutils.o qcore_unix.o qfilesystemengine_unix.o qfilesystemiterator_unix.o qfsfileengine_unix.o qlocale_unix.o  qlibraryinfo.o   -Wl,--gc-sections
/home/conda/feedstock_root/build_artifacts/qt-main_1654465491741/work/qt-build/qtbase/bin/qmake: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by andfoy** [comment]
This seems to be happening when bootstrapping qmake, which is unconventional, is `libstdc++` available on either `PREFIX` or `BUILD_PREFIX`?

**Comment by hmaarrfk** [comment]
[aarch.zip](https://github.com/conda-forge/qt-main-feedstock/files/8852819/aarch.zip)

I think i managed to build it.... I was trying to build 5.15.4 but forgot to change branches. I think @izahn had their main branch updated.

https://anaconda.org/mark.harfouche/qt-main/files

**Comment by hmaarrfk** [comment]
@andfoy do you want me to upload this build too? I guess it isn't really valuable since apparently it didn't affect linux.

**Comment by andfoy** [comment]
If you want, I can compile it myself and then ping you to upload it, whichever works fine for you! I wish there was a more clean way to ensure that the build completes under six hours

**Comment by hmaarrfk** [comment]
I already did build it.

You could try to break up qt-main into even smaller chunks though I think the build tools might be pretty large to build.

**Comment by andfoy** [comment]
Thanks! Then it's good to upload it, so that it is possible now to sync both webengine and main versions on qt

**Comment by hmaarrfk** [comment]
Thanks!
