### ISSUE TITLE
Incompatible qt-main and qt-webengine?

### ISSUE THREAD

**Issue by izahn** [conda-forge/qt-main-feedstock#36]
### Comment:

Trying to update the `rstudio-desktop` build I get 

```
 Could not find a configuration file for package "Qt5Quick" that is
  compatible with requested version "5.15.4".

  The following configuration files were considered but not accepted:

/home/conda/feedstock_root/build_artifacts/rstudio_1654353952872/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt5Quick/Qt5QuickConfig.cmake, version: 5.15.3
```

So basically only `qt-webengine=5.15.4` is available, but there is no corresponding `qt-main=5.15.4` yet. Is there any work-around, or do we just have to update qt-main as I started to do in https://github.com/conda-forge/qt-main-feedstock/pull/35 ?

**Comment by hmaarrfk** [comment]
they stopped release 5.15 "in time" for non-commercial users. for some reason, qt-webengine comes out earlier

**Comment by izahn** [comment]
I guess the other option is to build `qt-webengine=5.15.3`. Thoughts?

**Comment by izahn** [comment]
Yes, I still have a problem, but only because the `linux64` build of `qt-main` got stuck and was never uploaded to anaconda.org: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=518180&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97

Do you know how to unstick that?

**Comment by andfoy** [comment]
I think the problems are now fixed?

**Comment by hmaarrfk** [comment]
seems like it.

**Comment by izahn** [comment]
Yes, probably. I'm having other problems with the rstudio-desktop migration but unrelated to this.
