### ISSUE TITLE
Please restart master branch builds

### ISSUE THREAD

**Issue by akrherz** [conda-forge/qt-main-feedstock#4]
After the icu69 merge, I see the [master branch builds](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=425109&view=results) hit a transient conda issue.  Could they please be restarted so to get icu69 builds available :)

**Comment by Tobias-Fischer** [comment]
I triggered the failing builds again.

**Comment by ccordoba12** [comment]
Linux aarch64 doesn't build on CIs because it times out (which was already mentioned in https://github.com/conda-forge/qt-main-feedstock/pull/2#issuecomment-989279471).

@conda-forge/core, how that case should be handled so that people don't get the impression the build is failing?

**Comment by akrherz** [comment]
Hi @ccordoba12, indeed thanks.  I was referencing the others builds that failed due to the transient conda=4.10.3 issue.  I am interested in your question too.

**Comment by Tobias-Fischer** [comment]
In the past I uploaded the `qt` package for aarch somewhere (alongside build logs), and someone from core then uploaded it to the conda-forge channel (see https://github.com/conda-forge/qt-feedstock/pull/181).

@andfoy already offered to build the aarch packages this time around (see https://github.com/conda-forge/qt-main-feedstock/pull/2).

So the failing build in CI is fine as far as I understand, as the package will be uploaded manually.

**Comment by Tobias-Fischer** [comment]
linux-64 built successfully so closing here - feel free to open a separate issue re aarch
