### ISSUE TITLE
Upload aarch64 packages

### ISSUE THREAD

**Issue by andfoy** [conda-forge/qt-main-feedstock#5]
Hi, as we discussed in #2, I have now the compiled binaries for `aarch64`, I compiled it using the `build-locally` script, which was working exactly the same as on a `x86_64` machine. The packages are available here on my channel ready to copy them to conda-forge: https://anaconda.org/andfoy/qt-main

cc @conda-forge/core @conda-forge/qt-main

**Comment by andfoy** [comment]
@isuruf, is it possible to have any help with this one?

**Comment by isuruf** [comment]
Do you have the logs?

**Comment by andfoy** [comment]
I will need to save them to a file, I will reproduce them and post them here

**Comment by andfoy** [comment]
@isuruf, this is the build log for aarch64: https://drive.google.com/file/d/1mL-mGCryLw05PcuejwVRMSjHuB9ERXQR/view?usp=sharing

**Comment by andfoy** [comment]
@isuruf, is it possible to copy and upload this one?

**Comment by isuruf** [comment]
Done
