### ISSUE TITLE
Cross compiling project that links to qt6-main (osx-arm64 on x86_64 host)

### ISSUE THREAD

**Issue by cmeyer** [conda-forge/qt-main-feedstock#55]
### Comment:

I have a project built with cmake that links to the Qt 6 libraries.

When I try to build an arm64 version (the build is running on x86 instance), I install Qt 6 as a 'host' dependency (i.e. arm64). This allows cmake (with an addition of `export QT_HOST_PATH="$PREFIX"`) to find Qt 6 for my arm64 build and allow linking. However, Qt also requires running the `moc` tool. Unfortunately, this is not possible because the Qt 6 installed is arm64 and the `moc` tool has the wrong architecture to run on the x86 instance.

Is there any obvious solution to this?

Is it possible to distribute a fat version (arm64 + x86_64) of `qt6-main` instead of a processor specific version?

Here is the recipe / PR for the project in question: https://github.com/conda-forge/nionui-tool-feedstock/pull/32

**Comment by Tobias-Fischer** [comment]
Have you tried adding
```
- qt-main                         # [build_platform != target_platform]
```

To your `build` dependencies? This will install the x86_64 qt-main into the build environment, and you can then use the `moc` within there.

**Comment by cmeyer** [comment]
Thanks! That did the trick (along with setting `export QT_HOST_PATH="$BUILD_PREFIX") and a few other minor changes to finish the build.
