### ISSUE TITLE
Split off package for licensing and maintainability

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#78]
### Comment:

QtCharts comes with the GPLv3 only license.

It would be nice if we could split that off from the main package, which comes with LGPL.

See license at the top of this module
https://doc.qt.io/qt-5/qtcharts-index.html

There are a few other modules that may have the GPLv3 license.

let me know what you all think.

Staged recipes attempt at splitting off things into unique packages: 

* Staged Recipes Effort: https://github.com/conda-forge/staged-recipes/pull/21505
* Rendered feedstocks: https://github.com/orgs/qtforge/repositories
 * Azure CIs: https://dev.azure.com/markharfouche0439/feedstocks/_build

# Bulld order 

You can go through the `dependencies.yaml` file to see what things depend on what package.

| Submodule          | Linux | OSX | Windows | 
|--------------------|-----------|-------|-------- |
| qtbase             |   yes     |   yes | yes |
| qttools            |    yes   |  yes   | yes |
| qtsvg              |   yes        |  yes     | yes |
| qtimageformats     |  yes         |  yes     | yes |
| qtlanguageserver | qt6 only |  | |
| qtshadertools | qt6 only |    |   |
| qtdeclarative      |    yes   |       | yes |
| qtxmlpatterns      |           |       |
| qtscxml            |           |       |
| qtserialport       |           |       |
| qtserialbus        |           |       |
| qtquicktimeline    |           |       |
| qtquick3d          |           |       |
| qtmultimedia       |           |       |
| qtspeech           |           |       |
| qtscript           |           |       |
| qt3d               |           |       |
| qtremoteobjects    |           |       |
| qtopcua            |           |       |
| qtnetworkauth      |           |       |

Unsorted
| Submodule          | Linux | OSX | Windows | 
|--------------------|-----------|-------|-------- |
| qtgraphicaleffects |           |       |
| qtquickcontrols    |           |       |
| qtandroidextras    |           |       |
| qtpurchasing       |           |       |
| qtmqtt             |           |       |
| qtmacextras        |           |       |
| qtlottie           |           |       |
| qtlocation         |           |       |
| qtknx              |           |       |
| qtgamepad          |           |       |
| qtdoc              |           |       |
| qtdavis3d          |           |       |
| qtconnectivity     |           |       |
| qtcoap             |           |       |
| qtcharts           |           |       |
| qtactiveqt         |           |       |
| tqtc-qt5           |           |       |
| qtx11extras        |           |       |
| qtwinextras        |           |       |
| qtwebview          |           |       |
| qtwebsockets       |           |       |
| qtwebglplugins     |           |       |
| qtwebengine        |           |       |
| qtwebchannel       |           |       |
| qtvirtualkeyboard  |           |       |
| qtqttranslations   |           |       |
|                    |           |       |
|                    |           |       |
|                    |           |       |
|                    |           |       |
|                    |           |       |

**Comment by ccordoba12** [comment]
+1 from me.

**Comment by isuruf** [comment]
As I said in other threads, splitting off just qtcharts from qt-main is a -1 from me. If you want to do this, please split off all packages and let qt-main be a meta package. Changing the meaning of `qt-main` is not good.

**Comment by hmaarrfk** [comment]
> As I said in other threads, splitting off just qtcharts from qt-main is a -1 from me. If you want to do this, please split off all packages and let qt-main be a meta package. Changing the meaning of qt-main is not good.

This is a fine request.

Honestly, I don't think it is feasible to do the "master split off all at once".

I think we can hit a middle ground.

**Comment by jschueller** [comment]
that's for qt6, and I only did qt6-3d for now

**Comment by hmaarrfk** [comment]
Maybe we could  create a a `qt-base` package, that we communicate to other maintainers will continue to get "trimmed down" over time. 

We could use repo-data patches to ensure we don't break previously compiled packages, but recipes that depend on qt-core may break here and there as qt components get removed.

> that's for qt6, and I only did qt6-3d for now

Do you need a merge on that one, it seems that we decided to only keep a single feedstock, maybe "archive" the qt-6 stuff in a comment so we can get the package through?

**Comment by jschueller** [comment]
what do you mean keep a single feedstock ? put qt6-3d inside a branch of qt-main ?
for info its there for now: https://github.com/conda-forge/staged-recipes/pull/21050
I also think splitting qtcharts is a good idea

**Comment by hmaarrfk** [comment]
I think i got confused. you only removed qt3d from qt6, not qt5. I see.

**Comment by jschueller** [comment]
yes, only qt6, I dont want to break anything qt5

**Comment by hmaarrfk** [comment]
yeah. tbh, i don't know how of a way to break things off slowly. but without "breaking things off slowly", i fear that this is too big to bite off.

Maybe if we create a list of packages we want to break off, we can manage it over time.

**Comment by hmaarrfk** [comment]
I think we have an opportunity with qt 5.15.7 to split things off. I'm going to see how far i can get.

**Comment by hmaarrfk** [comment]
this was done for qt6. thank you @jschueller
