### ISSUE TITLE
Cannot build conda-forge package that depends on qt6-main on Windows

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/qt-main-feedstock#89]
### Comment:

Hello, our Windows builds on `conda-forge` with a dependency on `qt6-main` are reproducibly failing with the following error message:

> conda.CondaMultiError: Error with archive C:\Miniforge\pkgs\qt6-main-6.4.0-he608ae7_3.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:
> 
> failed with error: seeking backwards is not allowed
> 

Is the package damaged?

Here's the link to the build log: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=627142&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213

This is the respective PR where we see the problem: conda-forge/mnelab-feedstock#44

I also tried using `qt6-main` `6.4.1`, or other builds of `6.4.0`, but I end up with unresolvable dependencies due to `clang`-related constraints.

Thanks for any help and suggestions!

Richard

**Comment by hmaarrfk** [comment]
I think jschuller and I hit the issue in https://github.com/conda-forge/pyside2-feedstock/pull/154 and https://github.com/conda-forge/pyside2-feedstock/pull/153

**Comment by hoechenberger** [comment]
Thanks for the pointer, @hmaarrfk!! I'll be watching these PRs and close this issue once things are working.
