### ISSUE TITLE
PLUGIN_PATH seems to clash between qt6 and qt5

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#99]
### Comment:

In testing my build of https://github.com/conda-forge/qt-main-feedstock/pull/98 it seems that the plugin path is clashing between qt6 and qt5 causing them to not be able to be installed at the same time.

- Install that build of qt5 with the GTK plugin
- Install qt6

Try to run your application:
```
qt.core.plugin.loader: In /home/mark/mambaforge/envs/dev/plugins/platforms/libqoffscreen.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/dev/plugins/platforms/libqminimalegl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/dev/plugins/platforms/libqminimal.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/dev/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/dev/plugins/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/dev/plugins/platforms/libqwebgl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/dev/plugins/platforms/libqvnc.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by jschueller** [comment]
weird, I checked qt6-main and it install these in PREFIX/lib/qt6/plugins/platforms

**Comment by hmaarrfk** [comment]
It might be a clash between opencv loading in qt5 and python loading in qt6. More info to come.

**Comment by hmaarrfk** [comment]
I rebuilt opencv without qt support, and i can confirm that the problem is not due to opencv's linking to Qt.

it may be that it likes to search through `PREFIX/plugins` regardless.

**Comment by hmaarrfk** [comment]
So I went ahead and tried to compile QT5 with a different plugin path. I did not recompile PySide2.

After I recompiled it, I had to specify:

```
QT_PLUGIN_PATH=${CONDA_PREFIX}/lib/qt5/plugins
```
before starting my application otherwise I get an error like:

```
python -c "from PySide2.QtWidgets import QApplication; app = QApplication()"
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

I'm going to try to recompile PySide2 with the new build of qt-main that I have.

**Comment by hmaarrfk** [comment]
There seem to be a few more conflicts.

For example:

```
mamba create --name pyside6 pyside6 --channel conda-forge --override-channels
mamba activate pyside6
python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
# ^^^^^ This command should work
mamba install qt-main --channel conda-forge --override-channels
python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
# ^^^^^^ This will not work
```

```
qt.core.plugin.loader: In /home/mark/mambaforge/envs/pyside6/plugins/platforms/libqoffscreen.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/pyside6/plugins/platforms/libqminimalegl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/pyside6/plugins/platforms/libqminimal.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/pyside6/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/pyside6/plugins/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/pyside6/plugins/platforms/libqwebgl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mark/mambaforge/envs/pyside6/plugins/platforms/libqvnc.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```


Now if you install things from my channel (I've specified the plugin path on Linux for qt5 and built the GTK plugin with it)
```
mamba install mark.harfouche::qt-main --channel mark.harfouche --channel conda-forge --override-channels
```

You get an error:
```
python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```

But if you now specify:
```
QT_PLUGIN_PATH=${CONDA_PREFIX}/lib/qt6/plugins/ python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
```
Then it "works".

Uninstall qt-main will restore the functionality of 
```
python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
```

**Comment by hmaarrfk** [comment]
To summarize, if you try to install qt-main with pyside6, you can't run your pyside6 application due to it looking through the qt5 plugins unless something is changed with qt(5)-main

```
mamba create --name pyside6 pyside6 pyside2 --channel mark.harfouche --channel conda-forge --override-channels
mamba activate pyside6

python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
# ^^^ fails

QT_PLUGIN_PATH=${CONDA_PREFIX}/lib/qt6/plugins/ python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
# ^^^ works

mamba uninstall pyside2 qt-main

python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
# ^^^^ works

mamba install qt-main --channel conda-forge --override-channels

python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
# ^^^^^ Fails

QT_PLUGIN_PATH=${CONDA_PREFIX}/lib/qt6/plugins/ python -c "from PySide6.QtWidgets import QApplication; app = QApplication()"
# ^^^^^ also fails
```

**Comment by ccordoba12** [comment]
I think this is handled by [`qt.conf`](https://doc.qt.io/qt-6/qt-conf.html), but there's no attempt to write it in the Qt6 recipe (but there is in Qt5). I don't understand why because that's basically what makes Qt relocatable.

Furthermore, in order to have Qt5 and Qt6 living together in the same env, I think they'd need to point to different `qt.conf` files. So Qt6 would need to be patched to use `qt6.conf` and not `qt.conf` (I already mentioned that in https://github.com/conda-forge/qt-main-feedstock/issues/49#issuecomment-1247028989).

Until that's properly done, Qt6 support is semi-broken in conda-forge (unless we don't allow Qt6 to installed side-by-side with Qt5, but it seems that ship already sailed).

**Comment by jschueller** [comment]
where is this qt.conf ? I dont think qt6-main provides it

**Comment by ccordoba12** [comment]
It doesn't come with the with the package when it's compiled. It's a plain text file in ini format that it's adjusted by conda per environment to make the package relocatable. If you check the `build.sh` and `build.bat` scripts for the Qt5 recipe, you'll see that both have a way to handle that, which needs to be ported to the Qt6 recipe.

And besides that, you need to find where in the Qt6 code it looks for `qt.conf` and patch it so that it looks for `qt6.conf` instead (I don't know where that's declared, sorry).

**Comment by hmaarrfk** [comment]
The file might be:
https://github.com/qt/qtbase/blob/97165dbfa15118e197dd3ea28968d29141171a4d/src/corelib/global/qlibraryinfo.cpp#L115

qt6 looks like it might already look for the qt6.conf (at least on windows and linux, there seems to be some special logic for OSX)

**Comment by jschueller** [comment]
great, so conda should also provide a qt6.conf file alongside

**Comment by ccordoba12** [comment]
Yeah, that's really nice! It seems Qt looks for `qt6.conf` then `qt.conf`. Thanks @hmaarrfk for your help with that!

**Comment by ccordoba12** [comment]
> great, so conda should also provide a qt6.conf file alongside, no bug here

I don't understand what you meant by this, but you still need to make sure that the Qt6 conda recipe writes `qt6.conf` on env creation.

What @hmaarrfk found is that it's not necessary to patch Qt to make it detect `qt6.conf`.

**Comment by hmaarrfk** [comment]
>  you still need to make sure that the Qt6 conda 

I think you are both saying the same thing.

**Comment by ccordoba12** [comment]
Sorry if I sounded a bit too picky with my last message. I was just not sure if I understood @jschueller correctly, so I wanted to clarify what's missing.

**Comment by hmaarrfk** [comment]
No worries. I just really appreciate all your help in reviewing this. so I am excited to move the qt stuff forward. I feel like I have enough PRs that need reviewer (accross qt and opencv for this week) so I'm cooling off on major changes.

It was great to work through some of the troubleshooting steps with you both! I hope we got to the bottom of it.

**Comment by traversaro** [comment]
Just in case something is encountering the problem "qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in """ or "qt.qpa.plugin: Could not find the Qt platform plugin "windows" in """ for qt6 code in an environment with both qt-main and qt6-main installed, and found this issue in Google (as it happened to me). 

The PR https://github.com/conda-forge/qt-main-feedstock/pull/126 fixed the problem for executables that are installed in the `%CONDA_PREFIX%\Library\bin` dir on Windows or `$CONDA_PREFIX\bin` on unix, but if you have an executable in a custom directory (for example in a build directory) you can still have the same problem. A simple fix is to copy the `qt6.conf` in the folder where you have the executable you want to run, for example on unix:

~~~
cd /folder/where/your/executable/is
cp $CONDA_PREFIX/bin/qt6.conf ./
~~~

or command prompt on Windows:

~~~
cd .\folder\where\your\executable\is
copy %CONDA_PREFIX%\Library\bin\qt6.conf .\
~~~

**Comment by hmaarrfk** [comment]
i had this clash happen too for the `pyside-uic` command. I forget where i documented it.

we should likely reopen an issue for the binary clash if it doesn't exist.

**Comment by traversaro** [comment]
> we should likely reopen an issue for the binary clash if it doesn't exist.

I am working on this, and I was able to reproduce the problem without any qt-main installed in the env, so I guess it is not a problem of conflict.
